# Generated by Django 5.0.3 on 2024-03-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorEstudiantes', '0002_alter_estudiante_apellido_alter_estudiante_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
