# Generated by Django 5.0.3 on 2024-03-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicioClase9', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='_id',
            new_name='id',
        ),
    ]
